services:
  # NGINXサービス（既存）
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
  # MariaDBサービス
  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env

  # WordPressサービス
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    ports:
      - 9000:9000
    env_file:
      - .env
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/kahori/data/mariadb_data
      o: bind
      type: none
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/kahori/data/wordpress_data
      o: bind
      type: none

networks:
  inception_network:
    driver: bridge
