version: '3.8'

services:
  nginx:
    build:
      context: ./srcs/requirements/nginx
    ports:
      - "443:443" # HTTPS通信を外部に公開
    volumes:
      - ./data/nginx:/etc/nginx/conf.d # 設定ファイルをマウント
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
